version: 0.0
os: linux
files:
  - source: /
    destination: /opt/security-app
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root
