spring.application.name=security-app
spring.datasource.url=jdbc:postgresql://localhost:5432/security-app?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=install
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.security.user.name = siba
#spring.security.user.password = siba


jwt.secretKey = nheecyce88e889w8ew900q8ed77s87sd8s8ds8d788sd78sd7x8s7ds8x7s8d7xz78s7

deploy.env = development